name: shimmynote
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  cloud_firestore: 4.14.0
  cupertino_icons: ^1.0.2
  dynamic_color: 1.6.9
  firebase_auth: 4.16.0
  firebase_core: 2.24.2
  firebase_ui_auth: 1.12.1
  firebase_ui_oauth_google: 1.2.17
  flutter:
    sdk: flutter
  get: 4.6.6
  responsive_builder: 0.7.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
